# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 2) do

  create_table "comments", :force => true do |t|
    t.column "body",       :text
    t.column "subject",    :string
    t.column "email",      :string
    t.column "parent_id",  :integer
    t.column "content_id", :integer
    t.column "created_at", :datetime
  end

  add_index "comments", ["content_id"], :name => "fk_content_comments"

  create_table "companies", :force => true do |t|
    t.column "name",        :string, :limit => 40
    t.column "description", :string
  end

  create_table "contents", :force => true do |t|
    t.column "type",        :string
    t.column "title",       :string
    t.column "description", :string
    t.column "user_id",     :integer
    t.column "date",        :datetime
    t.column "content",     :text
    t.column "permalink",   :string
  end

  add_index "contents", ["user_id"], :name => "fk_user_contents"

  create_table "conversations", :force => true do |t|
    t.column "subject", :string
    t.column "type",    :string
  end

  create_table "polls", :force => true do |t|
    t.column "name",       :string
    t.column "created_at", :datetime
  end

  create_table "sections", :force => true do |t|
    t.column "body",       :text
    t.column "content_id", :integer
    t.column "title",      :string
    t.column "summary",    :string
    t.column "permalink",  :string
  end

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data",       :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["session_id"], :name => "index_sessions_on_session_id"
  add_index "sessions", ["updated_at"], :name => "index_sessions_on_updated_at"

  create_table "users", :force => true do |t|
    t.column "name",            :string
    t.column "hashed_password", :string
    t.column "salt",            :string
    t.column "firstname",       :string
    t.column "surname",         :string
    t.column "email",           :string
  end

  create_table "votes", :force => true do |t|
    t.column "poll_id", :integer
    t.column "option",  :string
    t.column "total",   :integer
  end

end
