# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 5) do

  create_table "articles", :force => true do |t|
    t.column "title",     :string
    t.column "content",   :text
    t.column "date",      :datetime
    t.column "author_id", :integer
    t.column "excerpt",   :text
    t.column "permalink", :string
  end

  add_index "articles", ["author_id"], :name => "author_id"

  create_table "articles_categories", :id => false, :force => true do |t|
    t.column "category_id", :integer
    t.column "article_id",  :integer
  end

  add_index "articles_categories", ["category_id"], :name => "category_id"
  add_index "articles_categories", ["article_id"], :name => "article_id"

  create_table "authors", :force => true do |t|
    t.column "username",  :string
    t.column "firstname", :string
    t.column "surname",   :string
    t.column "email",     :string
  end

  create_table "binaries", :force => true do |t|
    t.column "binary",       :binary
    t.column "content_type", :string
    t.column "size",         :string
    t.column "filename",     :string
  end

  create_table "categories", :force => true do |t|
    t.column "name",      :string
    t.column "permalink", :string
  end

  create_table "categories_cheatsheets", :id => false, :force => true do |t|
    t.column "category_id",   :integer
    t.column "cheatsheet_id", :integer
  end

  add_index "categories_cheatsheets", ["category_id"], :name => "category_id"
  add_index "categories_cheatsheets", ["cheatsheet_id"], :name => "cheatsheet_id"

  create_table "cheatsheets", :force => true do |t|
    t.column "thumbnail",              :binary
    t.column "pdf",                    :binary
    t.column "title",                  :string
    t.column "description",            :string
    t.column "author_id",              :integer
    t.column "date",                   :datetime
    t.column "filename",               :string
    t.column "content_type",           :string
    t.column "size",                   :integer
    t.column "thumbnail_size",         :integer
    t.column "thumbnail_content_type", :string
    t.column "counter",                :integer
    t.column "content",                :text
    t.column "permalink",              :string
  end

  add_index "cheatsheets", ["author_id"], :name => "author_id"

  create_table "comments", :force => true do |t|
  end

  create_table "companies", :force => true do |t|
    t.column "name",        :string, :limit => 40
    t.column "description", :string
  end

  create_table "portfolio_items", :force => true do |t|
    t.column "portfolio_type_id", :integer
    t.column "company_id",        :integer
    t.column "content_type",      :string
    t.column "filename",          :string
    t.column "size",              :integer
    t.column "data",              :binary
  end

  add_index "portfolio_items", ["portfolio_type_id"], :name => "portfolio_type_id"
  add_index "portfolio_items", ["company_id"], :name => "company_id"

  create_table "portfolio_types", :force => true do |t|
    t.column "description",         :string,  :limit => 40
    t.column "column_space",        :integer
    t.column "position",            :integer
    t.column "header_binary",       :binary
    t.column "header_filename",     :string
    t.column "header_content_type", :string
    t.column "visible",             :boolean,               :default => true
  end

  add_foreign_key "articles", ["author_id"], "authors", ["id"], :name => "articles_ibfk_1"

  add_foreign_key "articles_categories", ["category_id"], "categories", ["id"], :name => "articles_categories_ibfk_1"
  add_foreign_key "articles_categories", ["article_id"], "articles", ["id"], :name => "articles_categories_ibfk_2"

  add_foreign_key "categories_cheatsheets", ["category_id"], "categories", ["id"], :name => "categories_cheatsheets_ibfk_1"
  add_foreign_key "categories_cheatsheets", ["cheatsheet_id"], "cheatsheets", ["id"], :name => "categories_cheatsheets_ibfk_2"

  add_foreign_key "cheatsheets", ["author_id"], "authors", ["id"], :name => "cheatsheets_ibfk_1"

  add_foreign_key "portfolio_items", ["portfolio_type_id"], "portfolio_types", ["id"], :name => "portfolio_items_ibfk_1"
  add_foreign_key "portfolio_items", ["company_id"], "companies", ["id"], :name => "portfolio_items_ibfk_2"

end
