# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 19) do

  create_table "articles", :force => true do |t|
    t.column "title",     :string
    t.column "content",   :text
    t.column "date",      :datetime
    t.column "author_id", :integer
    t.column "excerpt",   :text
  end

  create_table "articles_categories", :id => false, :force => true do |t|
    t.column "category_id", :integer
    t.column "article_id",  :integer
  end

  create_table "authors", :force => true do |t|
    t.column "username",  :string
    t.column "firstname", :string
    t.column "surname",   :string
    t.column "email",     :string
  end

  create_table "binaries", :force => true do |t|
    t.column "binary",       :binary
    t.column "content_type", :string
    t.column "size",         :string
    t.column "filename",     :string
  end

  create_table "categories", :force => true do |t|
    t.column "name", :string
  end

  create_table "comments", :force => true do |t|
  end

  create_table "companies", :force => true do |t|
    t.column "name",        :string, :limit => 40
    t.column "description", :string
  end

  create_table "portfolio_items", :force => true do |t|
    t.column "portfolio_type_id", :integer
    t.column "company_id",        :integer
    t.column "content_type",      :string
    t.column "filename",          :string
    t.column "size",              :integer
    t.column "data",              :binary
  end

  add_index "portfolio_items", ["portfolio_type_id"], :name => "fk_portfolio_items_portfolio_types"
  add_index "portfolio_items", ["company_id"], :name => "fk_portfolio_items_companies"

  create_table "portfolio_types", :force => true do |t|
    t.column "description",         :string,  :limit => 40
    t.column "column_space",        :integer
    t.column "position",            :integer
    t.column "header_binary",       :binary
    t.column "header_filename",     :string
    t.column "header_content_type", :string
    t.column "visible",             :boolean,               :default => true
  end

end
